### ISSUE TITLE
Inverted QR code is not scannable

### ISSUE THREAD

**Issue by prusnak** [bennyguitar/BTCDonationViewController#1]
The code on the right is not scannable.

![img](https://raw.githubusercontent.com/bennyguitar/BTCDonationViewController/master/Images/figure2-01.png)

You cannot invert QR code colors, dark areas have to stay dark, light areas have to stay light. Also there has to be at least 1 pixel light bounding rectangle around the whole QR code. So if you want to show QR code on dark background it should look like this:

![img](http://www.ucview.com/images/digital-signage-qr-code.jpg)

**Comment by bennyguitar** [comment]
No, it just depends on the reader. Some readers are advanced enough to notice the pattern and invert the colors, and some don't do that.

In iOS7, QR codes are now natively detectable through the `AVFoundation` library which, through testing, picks up inverse QR codes. It scans the image just fine.

I've found these apps work out of the box with inverted QR codes:
- Scan - QR Code and Barcode Reader
- QR Reader for iPhone
- AT&T Code Scanner
- ScanLife: Barcode Scanner

These apps do not work correctly:
- Bakodo
- RedLaser
- QuickScan - QR Code Reader

With the problem actually residing in the implementation (or lack thereof) of true QR decoding, not actually in the format, I'm going to leave the ability to show light colors as the black lines for now.

**EDIT:**

I've skimmed through the 2005 specifications on QR codes and didn't notice anything outright about color format, though they showed inverted and mirrored options in there. I'll be glad to make the changes to reflect QR spec if that's the case.

Specs (you can find free versions online): http://www.iso.org/iso/catalogue_detail.htm?csnumber=43655
